### ISSUE TITLE
A function should do only one thing...

### ISSUE THREAD

**Issue by unimatrix099** [erosake/HeavierCoinDetector#2]
https://github.com/erosake/HeavierCoinDetector/blob/a90ac994ab23b966773768806be3a1fb94e0bfac/src/main/java/eros/generators/CoinGenerator.java#L14

this one: -generates weights
               -makes coins
               -and finally adds another coin in the end?

**Comment by erosake** [comment]
Solved with commit a6b6c9fcb1ec6296ff4125fffa583ad00824e6dd
